### PR TITLE
iampiyushgupta adds hometown of Mumbai

### PR DESCRIPTION
**Pull request by iampiyushgupta**
This PR is to add Mumbai to the list of cities in the class repo,

I don't have any questions .. :smile:

### CODE REVIEW

**Comment by ariestiyansyah** [comment]
Mumbai is good city, Hello from Indonesia

**Comment by stephen-murby** [comment]
> Is there any cricket on today?

@iampiyushgupta

**Comment by iampiyushgupta** [comment]
@stephen-murby There might be, I am more of a Soccer fan.!

**Comment by iampiyushgupta** [comment]
@ariestiyansyah  Hello from Mumbai..! :smile:

**Pull request merged**
